DROP TABLE USUARIOS_DAVID;

CREATE TABLE USUARIOS_DAVID(
ID NUMBER(11) NOT NULL,
IDENTIFICACION NUMBER(11) NOT NULL,
PRIMER_NOMBRE VARCHAR2(30)NOT NULL,
SEGUNDO_NOMBRE VARCHAR2(30) NULL,
PRIMER_APELLIDO VARCHAR2(30)NOT NULL,
SEGUNDO_APELLIDO VARCHAR2(30)NULL,
CONTRASENA VARCHAR2(10)NOT NULL,
PRIMARY KEY(ID)
)

CREATE SEQUENCE SEC_ID_USUARIOS_DAVID
START WITH 1
INCREMENT BY 1;


SELECT SEC_ID_USUARIOS_DAVID.CURRVAL FROM DUAL