CREATE TABLE USUARIOS_DAVID(
ID NUMBER(11) NOT NULL,
IDENTIFICACION NUMBER(11) NOT NULL,
NOMBRE VARCHAR2(30)NOT NULL,
APELLIDO1 VARCHAR2(30)NOT NULL,
APELLIDO2 VARCHAR2(30)NOT NULL,
DIRECCION VARCHAR2(30)NOT NULL,
EDAD NUMBER(3)NOT NULL,
PRIMARY KEY(ID)
)

CREATE SEQUENCE SEC_ID_USUARIOS_DAVID
START WITH 1
INCREMENT BY 1;

INSERT INTO USUARIOS_DAVID VALUES(SEC_ID_USUARIOS_DAVID.NEXTVAL,9485858,'CAMILA','HERRERA','OLMES','AV 85 - 33', 30)

SELECT * FROM USUARIOS_DAVID
SELECT SEC_ID_USUARIOS_DAVID.CURRVAL FROM DUAL